=== dviererbe/SVENSimulation/Assets/Roomdefinition/Schema_Raum.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Roomplan">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Room" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Height">
								<xs:simpleType>
									<xs:restriction base="xs:decimal"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Width">
								<xs:simpleType>
									<xs:restriction base="xs:decimal"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ThermalPixelSize">
								<xs:simpleType>
									<xs:restriction base="xs:decimal"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="WallThickness">
								<xs:simpleType>
									<xs:restriction base="xs:decimal"/>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Walls" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Window" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Position" type="Pos"/>
										<xs:element name="Size" type="Pos"/>
										<xs:element name="Rotation">
											<xs:simpleType>
												<xs:restriction base="xs:decimal"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Type">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Open"/>
													<xs:enumeration value="closed"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Door" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Position" type="Pos"/>
										<xs:element name="Size" type="Pos"/>
										<xs:element name="Rotation">
											<xs:simpleType>
												<xs:restriction base="xs:decimal"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Type">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Normal"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Furniture" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Chair" minOccurs="0" maxOccurs="unbounded"> 
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Position" type="Pos"/>
										<xs:element name="Size" type="Pos"/>
										<xs:element name="Rotation">
											<xs:simpleType>
												<xs:restriction base="xs:decimal"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Type">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Normal"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Table" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Position" type="Pos"/> <!-- Defiens the Position of the right Part of the Tabel -->
										<xs:element name="Size" type="Pos"/>
										<xs:element name="Rotation"> <!-- Positive Value = rotation counter clockwies-->
											<xs:simpleType>
												<xs:restriction base="xs:decimal"/>
											</xs:simpleType>
										</xs:element><xs:element name="Type">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Dozent"/>
													<xs:enumeration value="Student"/>
													<xs:enumeration value="Blank"/>
													<xs:enumeration value="Lecurehall"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>							
							</xs:element>
							<xs:element name="Heater" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Position" type="Pos"/>
										<xs:element name="Size" type="Pos"/>
										<xs:element name="Rotation"> <!-- Positive Value = rotation counter clockwies-->
											<xs:simpleType>
												<xs:restriction base="xs:decimal"/>
											</xs:simpleType>
										</xs:element><xs:element name="Type">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Default"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>							
							</xs:element>
							<xs:element name="Closet" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Position" type="Pos"/>
										<xs:element name="Size" type="Pos"/>
										<xs:element name="Rotation"> <!-- Positive Value = rotation counter clockwies-->
											<xs:simpleType>
												<xs:restriction base="xs:decimal"/>
											</xs:simpleType>
										</xs:element><xs:element name="Type">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Default"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>							
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Pos"> 
		<xs:sequence>
			<xs:element name="Height">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Width">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"/>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== dviererbe/SVENSimulation/Assets/Roomdefinition/9.428.xml
<?xml version="1.0" encoding="UTF-8"?>
<Roomplan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="F:\Unity\SVENSimulation\Assets\Roomdefinition\Schema_Raum.xsd">
    <Room>
        <Height>80</Height>
        <Width>98</Width>
        <ThermalPixelSize>1</ThermalPixelSize>
        <WallThickness>2</WallThickness>
        <Masseinheit>Dezimeter</Masseinheit>
    </Room>
    <Walls>
        <Window>
            <StartPosition>
                <Height>33</Height>
                <Width>97</Width>
            </StartPosition>
            <EndPosition>
                <Height>68</Height>
                <Width>97</Width>
            </EndPosition>
        </Window>
        <Door>
            <StartPosition>
                <Height>79</Height>
                <Width>71</Width>
            </StartPosition>
            <EndPosition>
                <Height>79</Height>
                <Width>91</Width>
            </EndPosition>
            <OpenDirecktion>south</OpenDirecktion>
        </Door>
        <Wall>
            <StartPosition>
                <Height>0</Height>
                <Width>0</Width>
            </StartPosition>
            <EndPosition>
                <Height>0</Height>
                <Width>97</Width>
            </EndPosition>
        </Wall>
        <Wall>
            <StartPosition>
                <Height>0</Height>
                <Width>0</Width>
            </StartPosition>
            <EndPosition>
                <Height>79</Height>
                <Width>0</Width>
            </EndPosition>
        </Wall>
        <Wall>
            <StartPosition>
                <Height>79</Height>
                <Width>0</Width>
            </StartPosition>
            <EndPosition>
                <Height>79</Height>
                <Width>70</Width>
            </EndPosition>
        </Wall>
        <Wall>
            <StartPosition>
                <Height>79</Height>
                <Width>92</Width>
            </StartPosition>
            <EndPosition>
                <Height>79</Height>
                <Width>97</Width>
            </EndPosition>
        </Wall>
        <Wall>
            <StartPosition>
                <Height>0</Height>
                <Width>97</Width>
            </StartPosition>
            <EndPosition>
                <Height>33</Height>
                <Width>97</Width>
            </EndPosition>
        </Wall>
        <Wall>
            <StartPosition>
                <Height>69</Height>
                <Width>97</Width>
            </StartPosition>
            <EndPosition>
                <Height>79</Height>
                <Width>97</Width>
            </EndPosition>
        </Wall>
    </Walls>
    <Furniture>
        <Chair>
            <Position>
                <Height>15</Height>
                <Width>7.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>-90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>22</Height>
                <Width>7.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>-90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>31</Height>
                <Width>7.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>-90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>38</Height>
                <Width>7.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>-90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>47</Height>
                <Width>7.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>-90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>54</Height>
                <Width>7.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>-90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>53</Height>
                <Width>26.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>46</Height>
                <Width>26.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>37</Height>
                <Width>26.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>30</Height>
                <Width>26.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>8.5</Height>
                <Width>21</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>0</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>8.5</Height>
                <Width>28</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>0</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>8.5</Height>
                <Width>37</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>0</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>8.5</Height>
                <Width>44</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>0</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>8.5</Height>
                <Width>53</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>0</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>8.5</Height>
                <Width>60</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>0</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>8.5</Height>
                <Width>69</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>0</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>8.5</Height>
                <Width>75</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>0</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>14</Height>
                <Width>90.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>21</Height>
                <Width>90.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>30</Height>
                <Width>90.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>90</Rotation>
            <Type>Normal</Type>
        </Chair>
        <Chair>
            <Position>
                <Height>37</Height>
                <Width>90.5</Width>
            </Position>
            <Size>
                <Height>0.6</Height>
                <Width>0.6</Width>
            </Size>
            <Rotation>90</Rotation>
            <Type>Normal</Type>
